# Generated by Django 2.1.5 on 2019-01-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorid', models.AutoField(db_column='AuthorID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Author',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(db_column='BookID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=45, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('pubdate', models.DateTimeField(blank=True, db_column='PubDate', null=True)),
                ('authorid', models.ForeignKey(blank=True, db_column='AuthorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Author')),
            ],
            options={
                'db_table': 'Book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='CIty', max_length=45, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=2, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=10, null=True)),
                ('discountpct', models.DecimalField(blank=True, db_column='DiscountPct', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('priceid', models.AutoField(db_column='PriceId', primary_key=True, serialize=False)),
                ('listprice', models.DecimalField(blank=True, db_column='ListPrice', decimal_places=2, max_digits=10, null=True)),
                ('bookid', models.ForeignKey(blank=True, db_column='BookID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Book')),
            ],
            options={
                'db_table': 'Price',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherid', models.AutoField(db_column='PublisherID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=45, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=45, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=2, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Publisher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('saleid', models.AutoField(db_column='SaleID', primary_key=True, serialize=False)),
                ('saledate', models.DateTimeField(blank=True, db_column='SaleDate', null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('saleprice', models.DecimalField(blank=True, db_column='SalePrice', decimal_places=2, max_digits=10, null=True)),
                ('bookid', models.ForeignKey(blank=True, db_column='BookID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Book')),
                ('customerid', models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Customer')),
            ],
            options={
                'db_table': 'Sale',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisherid',
            field=models.ForeignKey(blank=True, db_column='PublisherID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.Publisher'),
        ),
    ]
